### PR TITLE
bump cuda base image to 12.5.0

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Review by cdesiniotis — APPROVED** [review]
Thanks @tariq1890. We should configure dependabot to do this for us in the future.

**Comment by tariq1890** [comment]
> Thanks @tariq1890. We should configure dependabot to do this for us in the future.

In that case, we would need to stop using the variables and reference the cuda base image explicitly

**Comment by tariq1890** [comment]
Triggered gitlab pipeline to build dev images for testing: https://gitlab.com/nvidia/container-images/driver/-/pipelines/1329888983

**Comment by tariq1890** [comment]
Kicked off gitlab pipeline to build dev images for testing: https://gitlab.com/nvidia/container-images/driver/-/pipelines/1329888983

**Comment by tariq1890** [comment]
The following images have been tested :

```
registry.gitlab.com/nvidia/container-images/driver:60b9d046-535.183.01-ubuntu22.04
registry.gitlab.com/nvidia/container-images/driver:60b9d046-550.90.07-ubuntu22.04
```

**Pull request merged**
